### ISSUE TITLE
Set readOnlyRootFilesystem to true for all containers

### ISSUE THREAD

**Issue by timp87** [metal-stack/helm-charts#66]
My proposal is to set (hardcode) **readOnlyRootFilesystem** to **true** for all containers [securityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#securitycontext-v1-core).

I find this a nice security measure and in my experience many companies enforce this setting to be on for all containers. General rule in such case is to explicitly state what volumes should be mounted.
I have tried running csi-driver-lvm (0.5.3) storage class containers (all 6 containers) with readOnlyRootFilesystem set to true and found only [one problem](https://github.com/metal-stack/helm-charts/pull/65).
If we agree here I can prepare a PR.

**Comment by chbmuc** [comment]
Sure! I think this will be a useful security improvement. Please go ahead and send a PR.

**Comment by timp87** [comment]
Closing this issue. We may continue discussion in https://github.com/metal-stack/helm-charts/pull/67 if needed
